name: Simple-apple-auth

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    # - name: Publish to npm
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   run: |
    #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    #     npm publish
